USE [Amadeus5]
GO

/****** Object:  Table [dbo].[CodesPIN]    Script Date: 09/12/2024 15:08:05 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CodesPIN](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Societe] [nvarchar](255) NOT NULL,
	[Semaine] [int] NOT NULL,
	[Annee] [int] NOT NULL,
	[Pin] [char](4) NOT NULL,
	[Utilise] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Societe] ASC,
	[Semaine] ASC,
	[Annee] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CodesPIN] ADD  DEFAULT ((0)) FOR [Utilise]
GO


